# Generated by Django 5.2.7 on 2026-02-19 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_categhory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categhory',
            new_name='Category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.category', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
