# Generated by Django 5.2.7 on 2026-03-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_image_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='img/def_img.csv', null=True, upload_to='productes/', verbose_name='Photo'),
        ),
    ]
